### ISSUE TITLE
Image preload won't work with cross-domain image

### ISSUE THREAD

**Issue by kayue** [gocom/dense#6]
If user is using a CDN or loading external image, the AJAX preload method won't work because of cross-domain issue.

https://github.com/gocom/dense/blob/master/src/dense.js#L211-L224

I think creating an `Image` element is better here.

```
$img = new Image();
$img.src = "//preload-me.com/image.jpg";
```

**Comment by gocom** [comment]
It's not pre-loading any data; it's sending HEAD request to verify whether the image exists.
